import { Stay } from '../types/stay';

export const CATEGORIES = [
  { id: 'all', name: 'Tất cả', icon: 'Compass' },
  { id: 'Trending', name: 'Nổi bật', icon: 'Flame' },
  { id: 'Beachfront', name: 'Bãi biển', icon: 'Umbrella' },
  { id: 'Cabins', name: 'Nhà gỗ', icon: 'TreePine' },
  { id: 'Mountain', name: 'Núi cao', icon: 'Mountain' },
  { id: 'Luxury', name: 'Sang trọng', icon: 'Crown' },
  { id: 'Lakefront', name: 'Ven hồ', icon: 'Waves' },
];

export const MOCK_STAYS: Stay[] = [
  {
    id: 'stay-1',
    title: 'The Pine Hill Wooden Villa & Cloud View',
    tagline: 'Ngắm biển mây ngàn tại thành phố mộng mơ Đà Lạt',
    description: 'Biệt thự nhà gỗ cao cấp ẩn mình giữa đồi thông xanh ngát tại Đà Lạt. Tận hưởng không khí se lạnh buổi sáng, thưởng thức cà phê và ngắm nhìn toàn cảnh thung lũng mây huyền ảo.',
    type: 'Villa',
    category: 'Cabins',
    pricePerNight: 1250000,
    cleaningFee: 200000,
    serviceFee: 100000,
    location: {
      city: 'Đà Lạt',
      province: 'Lâm Đồng',
      address: 'Số 15 Phường 3, Đường Hùng Vương, Đà Lạt',
    },
    rating: 4.92,
    reviewCount: 128,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'wifi', name: 'Wi-Fi tốc độ cao', icon: 'Wifi' },
      { id: 'fireplace', name: 'Lò sưởi ấm áp', icon: 'Flame' },
      { id: 'kitchen', name: 'Bếp đầy đủ dụng cụ', icon: 'Utensils' },
      { id: 'bbq', name: 'Khu vực nướng BBQ', icon: 'ChefHat' },
      { id: 'parking', name: 'Chỗ đỗ xe miễn phí', icon: 'Car' },
    ],
    host: {
      id: 'host-1',
      name: 'Minh Anh',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 3, 2021',
      responseRate: '100%',
    },
    isFeatured: true,
  },
  {
    id: 'stay-2',
    title: 'Phú Quốc Sunset Luxury Beach Bungalow',
    tagline: 'Bước một bước ra bãi cát trắng ngọc Phú Quốc',
    description: 'Bungalow ven biển thiết kế phong cách Địa Trung Hải với hồ bơi vô cực nhìn thẳng ra đại dương. Thích hợp cho cặp đôi và gia đình nghỉ dưỡng.',
    type: 'Resort',
    category: 'Beachfront',
    pricePerNight: 2800000,
    cleaningFee: 300000,
    serviceFee: 200000,
    location: {
      city: 'Phú Quốc',
      province: 'Kiên Giang',
      address: 'Bãi Trường, Dương Tơ, Phú Quốc',
    },
    rating: 4.96,
    reviewCount: 215,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'pool', name: 'Hồ bơi riêng', icon: 'Waves' },
      { id: 'beach', name: 'Bãi biển riêng', icon: 'Umbrella' },
      { id: 'ac', name: 'Điều hòa 2 chiều', icon: 'Wind' },
      { id: 'breakfast', name: 'Bữa sáng miễn phí', icon: 'Coffee' },
    ],
    host: {
      id: 'host-2',
      name: 'Elena Nguyễn',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 8, 2019',
      responseRate: '99%',
    },
    isFeatured: true,
  },
  {
    id: 'stay-3',
    title: 'Sapa Terrace Rice Field Eco Lodge',
    tagline: 'Hòa mình giữa ruộng bậc thang Mường Hoa lung linh',
    description: 'Eco Lodge gỗ mây tre mộc mạc ngắm trọn thung lũng ruộng bậc thang Sapa. Không gian yên bình thư thái, phục vụ ẩm thực Tây Bắc đặc sắc.',
    type: 'Homestay',
    category: 'Mountain',
    pricePerNight: 950000,
    cleaningFee: 150000,
    serviceFee: 80000,
    location: {
      city: 'Sapa',
      province: 'Lào Cai',
      address: 'Bản Tả Van, Thung lũng Mường Hoa, Sapa',
    },
    rating: 4.88,
    reviewCount: 94,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    images: [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'wifi', name: 'Wi-Fi', icon: 'Wifi' },
      { id: 'heater', name: 'Máy sưởi ấm', icon: 'Flame' },
      { id: 'mountain_view', name: 'View núi & ruộng', icon: 'Mountain' },
    ],
    host: {
      id: 'host-3',
      name: 'A Chảo',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      isSuperhost: false,
      joinedDate: 'Tháng 1, 2022',
      responseRate: '95%',
    },
    isFeatured: false,
  },
  {
    id: 'stay-4',
    title: 'Da Nang Oceanfront Highrise Penthouse',
    tagline: 'Căn hộ Penthouse đẳng cấp view trọn bãi biển Mỹ Khê',
    description: 'Căn hộ Penthouse cao cấp tầng 32 với ban công toàn cảnh biển Đà Nẵng và cầu Rồng. Trang thiết bị hiện đại 5 sao, hồ bơi vô cực tầng thượng.',
    type: 'Apartment',
    category: 'Luxury',
    pricePerNight: 3500000,
    cleaningFee: 350000,
    serviceFee: 250000,
    location: {
      city: 'Đà Nẵng',
      province: 'Đà Nẵng',
      address: 'Võ Nguyên Giáp, Quận Sơn Trà, Đà Nẵng',
    },
    rating: 4.98,
    reviewCount: 310,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'pool', name: 'Hồ bơi vô cực', icon: 'Waves' },
      { id: 'gym', name: 'Phòng Gym 24/7', icon: 'Dumbbell' },
      { id: 'elevator', name: 'Thang máy thẻ từ', icon: 'Building' },
      { id: 'smart_tv', name: 'Smart TV 75 inch', icon: 'Tv' },
    ],
    host: {
      id: 'host-4',
      name: 'Hoàng Nam',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 5, 2020',
      responseRate: '100%',
    },
    isFeatured: true,
  },
];
