import { Stay } from '../types/stay';
import { RewardVoucher, MemberTier } from '../types/reward';

export const CATEGORIES = [
  { id: 'all', name: 'Tất cả', icon: 'Grid' },
  { id: 'Hotel', name: 'Khách sạn', icon: 'Building2' },
  { id: 'Homestay', name: 'Homestay', icon: 'Home' },
  { id: 'Resort', name: 'Khu nghỉ dưỡng', icon: 'Trees' },
  { id: 'Villas', name: 'Biệt thự', icon: 'Castle' },
];

export const MOCK_STAYS: Stay[] = [
  {
    id: 'stay-alpine',
    title: 'The Alpine Lodge',
    tagline: 'Khu nghỉ dưỡng phong cách Thụy Sĩ giữa đồi thông xanh ngát',
    description: 'Biệt thự gỗ Alpine thiết kế sang trọng với view ngắm thung lũng sương mù. Phù hợp cho chuyến nghỉ dưỡng thư thái cùng gia đình.',
    type: 'Villas',
    category: 'Cabins',
    pricePerNight: 850000,
    cleaningFee: 150000,
    serviceFee: 80000,
    distanceKm: 2.5,
    cityArea: 'Đồi Thông Phường 3',
    location: {
      city: 'Đà Lạt',
      province: 'Lâm Đồng',
      address: 'Đường Hùng Vương, Phường 3, Đà Lạt',
    },
    rating: 4.8,
    reviewCount: 156,
    maxGuests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'wifi', name: 'Wi-Fi tốc độ cao', icon: 'Wifi' },
      { id: 'fireplace', name: 'Lò sưởi ấm', icon: 'Flame' },
      { id: 'parking', name: 'Đỗ xe miễn phí', icon: 'Car' },
    ],
    host: {
      id: 'host-1',
      name: 'Minh Anh',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 3, 2021',
      responseRate: '100%',
    },
    roomTiers: [
      {
        id: 'rt-101',
        name: 'Phòng Alpine Deluxe Mountain View',
        description: 'Phòng giường đôi ban công rộng ngắm view thung lũng',
        sizeSqm: 42,
        bedType: '1 Giường King',
        pricePerNight: 850000,
        originalPrice: 1050000,
        maxGuests: 2,
        includesBreakfast: true,
        cancellationPolicy: 'Miễn phí hủy trước 48h',
        availableCount: 3,
      },
      {
        id: 'rt-102',
        name: 'Phòng Alpine Family Suite 2 Bedrooms',
        description: 'Suite gia đình 2 phòng ngủ riêng biệt',
        sizeSqm: 75,
        bedType: '2 Giường King',
        pricePerNight: 1650000,
        originalPrice: 1950000,
        maxGuests: 4,
        includesBreakfast: true,
        cancellationPolicy: 'Miễn phí hủy trước 7 ngày',
        availableCount: 2,
      },
    ],
    priceComparisons: [
      { providerName: 'StayFinder Direct', pricePerNight: 850000, isBestValue: true },
      { providerName: 'Agoda Official', pricePerNight: 920000 },
      { providerName: 'Booking.com', pricePerNight: 950000 },
    ],
    isFeatured: true,
    isRecommended: true,
  },
  {
    id: 'stay-desert',
    title: 'Desert Oasis Resort',
    tagline: 'Khu nghỉ dưỡng ven biển thiết kế Địa Trung Hải ấn tượng',
    description: 'Resort cao cấp ven biển với hồ bơi vô cực rộng 500m2 ngắm hoàng hôn rực rỡ.',
    type: 'Resort',
    category: 'Beachfront',
    pricePerNight: 1200000,
    cleaningFee: 200000,
    serviceFee: 100000,
    distanceKm: 5.0,
    cityArea: 'Bãi Trường',
    location: {
      city: 'Phú Quốc',
      province: 'Kiên Giang',
      address: 'Bãi Trường, Dương Tơ, Phú Quốc',
    },
    rating: 4.9,
    reviewCount: 230,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'pool', name: 'Hồ bơi vô cực', icon: 'Waves' },
      { id: 'beach', name: 'Bãi biển riêng', icon: 'Umbrella' },
      { id: 'breakfast', name: 'Bữa sáng miễn phí', icon: 'Coffee' },
    ],
    host: {
      id: 'host-2',
      name: 'Elena Nguyễn',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 8, 2019',
      responseRate: '99%',
    },
    roomTiers: [
      {
        id: 'rt-201',
        name: 'Oceanfront Villa with Private Pool',
        description: 'Villa bãi biển có bể bơi riêng biệt',
        sizeSqm: 90,
        bedType: '1 Giường Super King',
        pricePerNight: 1200000,
        maxGuests: 2,
        includesBreakfast: true,
        cancellationPolicy: 'Miễn phí hủy trước 3 ngày',
        availableCount: 4,
      },
    ],
    priceComparisons: [
      { providerName: 'StayFinder Direct', pricePerNight: 1200000, isBestValue: true },
      { providerName: 'Expedia Partner', pricePerNight: 1350000 },
    ],
    isFeatured: true,
    isRecommended: true,
  },
  {
    id: 'stay-urban',
    title: 'Urban Loft Downtown',
    tagline: 'Căn hộ Loft hiện đại trung tâm thành phố sôi động',
    description: 'Loft thiết kế không gian mở với cửa kính tràn viền ngắm toàn cảnh thành phố về đêm.',
    type: 'Homestay',
    category: 'Trending',
    pricePerNight: 650000,
    cleaningFee: 100000,
    serviceFee: 50000,
    distanceKm: 1.2,
    cityArea: 'Trung tâm thành phố (City Center)',
    location: {
      city: 'Đà Nẵng',
      province: 'Đà Nẵng',
      address: 'Đường Nguyễn Văn Linh, Quận Thanh Khê, Đà Nẵng',
    },
    rating: 4.7,
    reviewCount: 128,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'wifi', name: 'Wi-Fi', icon: 'Wifi' },
      { id: 'ac', name: 'Điều hòa', icon: 'Wind' },
      { id: 'smart_tv', name: 'Smart TV 65"', icon: 'Tv' },
    ],
    host: {
      id: 'host-3',
      name: 'Hoàng Nam',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      isSuperhost: false,
      joinedDate: 'Tháng 5, 2022',
      responseRate: '98%',
    },
    isPopularNearYou: true,
  },
  {
    id: 'stay-ivy',
    title: 'Ivy Boutique Hotel',
    tagline: 'Khách sạn phong cách Tân cổ điển sang trọng tại Phố Cổ',
    description: 'Khách sạn nhỏ ấm cúng nằm tại trái tim Phố Cổ, phong cách thiết kế Pháp tinh tế.',
    type: 'Hotel',
    category: 'Luxury',
    pricePerNight: 950000,
    cleaningFee: 120000,
    serviceFee: 70000,
    distanceKm: 0.8,
    cityArea: 'Khu Phố Cổ (Old Town)',
    location: {
      city: 'Hà Nội',
      province: 'Hà Nội',
      address: 'Phố Hàng Bè, Quận Hoàn Kiếm, Hà Nội',
    },
    rating: 4.5,
    reviewCount: 84,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'wifi', name: 'Wi-Fi', icon: 'Wifi' },
      { id: 'elevator', name: 'Thang máy', icon: 'Building' },
    ],
    host: {
      id: 'host-4',
      name: 'Quỳnh Trang',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
      isSuperhost: true,
      joinedDate: 'Tháng 10, 2020',
      responseRate: '100%',
    },
    isPopularNearYou: true,
  },
];

export const MOCK_USER_TIER: MemberTier = {
  name: 'VIP',
  currentPoints: 2450,
  nextTierPoints: 5000,
  benefits: [
    'Giảm thêm 10% cho mọi đơn đặt phòng',
    'Miễn phí nâng hạng phòng (khi có sẵn)',
    'Nhận phòng sớm & Trả phòng muộn 2h',
    'Hỗ trợ ưu tiên 24/7',
  ],
};

export const MOCK_VOUCHERS: RewardVoucher[] = [
  {
    id: 'v-101',
    title: 'Giảm 20% Đặt phòng lần đầu',
    code: 'STAYWELCOME20',
    discountPercentage: 20,
    minSpend: 500000,
    expiryDate: '31/12/2026',
    pointsRequired: 0,
    isUnlocked: true,
    category: 'Discount',
  },
  {
    id: 'v-102',
    title: 'Miễn phí Buffet Bữa sáng',
    code: 'FREEBREAKFAST',
    minSpend: 800000,
    expiryDate: '15/11/2026',
    pointsRequired: 500,
    isUnlocked: true,
    category: 'FreeBreakfast',
  },
  {
    id: 'v-103',
    title: 'Voucher Đêm nghỉ Khách sạn VIP',
    code: 'VIPSTAY500K',
    discountAmount: 500000,
    minSpend: 2000000,
    expiryDate: '20/12/2026',
    pointsRequired: 1500,
    isUnlocked: false,
    category: 'Discount',
  },
];
